import "./globals.css";
import Link from "next/link";
import { Inter } from "next/font/google";
export const metadata = {
  title: "learn next13",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <div className="container mx-auto">
            <div className="flex items-center justify-between">
              <div>
                <Link href="/">
                  <h2 className="text-xl lg:text-2xl text-primary font-bold">
                    Navbar
                  </h2>
                </Link>
              </div>
              <nav className="py-4 flex gap-4">
                <Link href="/" className="hover:text-primary">
                  Home
                </Link>
                <Link href="/post" className="hover:text-primary">
                  Product
                </Link>
              </nav>
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
